### ISSUE TITLE
[Vanilla Bug] To edit Tiberium in a map, [Tiberiums] must be relisted

### ISSUE THREAD

**Issue by Crimsonum** [Vinifera-Developers/Vinifera#576] opened 2021-09-24 09:03 UTC
### Description:
When editing any of the Tiberium types in a map, the ``[Tiberiums]`` list must also be included in the map, else the changes are ignored.

**Comment by E1Elite** [comment] 2021-09-24 09:46
Basically, its index has to be re-declared in the map. For example, to modify Color of Vinifera, you need the following in map:

[Tiberiums]
2=abc ; any literal

[Vinifera]
Color=DarkOrange

**Comment by CCHyper** [comment] 2021-09-27 11:16
While I can see how this might be observed as a bug compared to the expected loading style of other types in the game, this is in fact by design. As @E1Elite mentioned, the `[Tiberiums]` section must be redefined for it to process that entry.

Closing the issue as this is designed behaviour.

**Closed by CCHyper** 2021-09-27 11:16 UTC
Labels: vanilla-bug
