### ISSUE TITLE
[New Feature] Recoil for turrets

### ISSUE THREAD

**Issue by Bittah** [Vinifera-Developers/Vinifera#430] opened 2021-06-25 02:41 UTC
### Description:
Recoil for turrets like in RA1. In RA1 turrets of units and structures move a pixel backwards every time a shot is fired.

### Possible Implementation:
Allow `TurretRecoil=true` to be specified for individual units and structures in Rules.ini.

**Comment by Rampastring** [comment] 2021-06-25 07:21
Duplicate of #142

**Closed by Rampastring** 2021-06-25 07:21 UTC
Labels: new-feature
