### ISSUE TITLE
[New Feature] Change drop pod infantry.

### ISSUE THREAD

**Issue by MikillRosen** [Vinifera-Developers/Vinifera#499] opened 2021-07-06 16:04 UTC
### Description:
Drop Pods are hard-coded to spawn light infantry and disk throwers and that can only be changed by hex editing. It would be nice to be able to change this easily with INI editing.

### Possible Implementation:
`DropPodInfantry=` is applicable to the [General] section and the `DropPodSpecial` support power and it accepts multiple InfantryTypes. Defaults to `E1,E2`

**Comment by KajiTetsushi** [comment] 2023-01-22 19:06
@MikillRosen this looks like a duplicate of #258, I suppose you're referring to the same problem, too?

**Comment by Rampastring** [comment] 2023-01-22 20:28
Closing this as a duplicate.

**Closed by Rampastring** 2023-01-22 20:28 UTC
Labels: new-feature
