### ISSUE TITLE
[Vanilla Bug] Enforce a minimum burst of 1 to avoid crashes

### ISSUE THREAD

**Issue by Bittah** [Vinifera-Developers/Vinifera#1139] opened 2024-10-30 01:04 UTC
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, debug and exception logs, etc)*.

### Description

Fix common crash at 0047f938 caused by bad mods with `Burst=0` in weapontypes.

### Required Code (optional)

```ini
[SOMEWEAPON]
Burst=0
```

### Steps To Reproduce

.

### Expected Behaviour

.

### Actual Behaviour

.

### Additional Context

Fixed in ts-patches: https://github.com/CnCNet/ts-patches/blob/master/src/minimum_burst.asm

**Comment by ZivDero** [comment] 2024-10-30 05:09
Duplicate of #613

**Closed by ZivDero** 2024-10-30 05:09 UTC
Labels: vanilla-bug
