### ISSUE TITLE
[Vanilla Bug] Trigger difficulty flags don't work

### ISSUE THREAD

**Issue by Crimsonum** [Vinifera-Developers/Vinifera#299] opened 2021-06-08 18:13 UTC
### Description:
Map triggers have three flags meant to toggle which difficulty setting(s) they should be enabled on. However, these flags don't work, instead triggers are enabled on all difficulty modes.

Example:
```ini
[Triggers]
01000000=GDI,<none>,Hard trigger,0,0,0,1,0
01000002=GDI,<none>,Medium trigger,0,0,1,0,0
01000004=GDI,<none>,Easy trigger,0,1,0,0,0
```

The 4th to 2nd last comma-separated values are the toggles for easy, medium, and hard difficulty, respectively. As you can see, each of these triggers is supposed to be enabled for only one of the difficulty modes.

### Steps To Reproduce:
Play the attached test map (put it in your TS folder and launch the GDI campaign).

### Expected Behaviour:
One of three tutorial text lines should be printed depending on the difficulty selected.

### Actual Behaviour:
All three text lines are printed:
![image](https://user-images.githubusercontent.com/17765965/121235755-ddb55000-c89d-11eb-9f5a-9175f3e895e9.png)

### Additional Files:
[gdi1a.zip](https://github.com/Vinifera-Developers/Vinifera/files/6618723/gdi1a.zip)

**Comment by CCHyper** [comment] 2021-06-09 12:30
Looks like the trigger INI reading code actually only sets the value when it is "true" for the respective difficulty, but each TriggerType is initialised with the respective difficulty set to "true", so they never get set to "false"...

**Comment by CCHyper** [comment] 2023-02-22 20:34
This issue was incorrectly closed by the GitHub bot, reopening.

**Comment by CCHyper** [comment] 2023-02-24 11:03
The bugfix was confirmed to be working by @Bittah, changes are now pushed upstream. Closing the issue.

**Closed by CCHyper** 2023-02-24 11:03 UTC
Labels: vanilla-bug
