### ISSUE TITLE
[Vanilla Bug] Side-specific music doesn't work in skirmish/multiplayer

### ISSUE THREAD

**Issue by Crimsonum** [Vinifera-Developers/Vinifera#704] opened 2021-10-25 18:38 UTC
### Description:
The `Side` key in `theme(01).ini` specifies which side(s), `GDI` and/or `Nod`, can hear the music track and select it in the in-game jukebox. However, in skirmish and online multiplayer, players are interpreted as "GDI" regardless of which side they actually play as, so any themes with `Side=Nod` are never heard by the players.

### Steps To Reproduce:
1. Go to Skirmish/Multiplayer.
2. Play as Nod.
3. Select the in-game jukebox.

### Expected Behaviour:
The player should see Nod-specific tracks like Defense and Nod Crush, while GDI-specific tracks like Lone Troop [sic] should *not* be available.

### Actual Behaviour:
Only shared and GDI-specific tracks are available.

**Comment by CCHyper** [comment] 2023-03-31 02:46
@Crimsonum Vinifera prints a warning if it detects error, and suggests that `Side=` of `[Nod]` is changed to `Nod`.

Closing this issue as the feature works as intended.

**Closed as completed by CCHyper** 2023-03-31 02:46 UTC
Labels: vanilla-bug
