### ISSUE TITLE
[New Feature] Force lasers to always be drawn with detail level 1

### ISSUE THREAD

**Issue by Bittah** [Vinifera-Developers/Vinifera#1137] opened 2024-10-30 00:53 UTC
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, videos, links, etc)*.

### Description

Lasers with detail level 2 are known to often crash the game when firing beyond the bottom of the screen in vanilla TS and forcing them to detail level 1 prevents the crash.

While the renderers included with the TS Client (cnc-ddraw, ts-ddraw and DDrawCompat) already fix this crash for as far as I know, DTA still needs detail level 1 lasers in order to make them look thin enough to match the TD Obelisk of Light structure (the lasers look wider than the structure itself otherwise). So we need a key that forces detail level 1 lasers.

### Additional Context

Implemented via ts-patches: https://github.com/CnCNet/ts-patches/blob/master/src/laser_draw_it_crash.asm

**Comment by ZivDero** [comment] 2024-10-30 05:08
Duplicate of #78

**Closed by ZivDero** 2024-10-30 05:08 UTC
Labels: new-feature
