### ISSUE TITLE
[Vanilla Bug] Fixing movie scaling

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#151] opened 2021-05-12 21:59 UTC
### Description:
According to FunkyFr3sh, there are some cases when the game scales movies too much, resulting in them being partially cut off on the screen. I don't have further details.

### Additional Files:
Fixed in CnCNet ts-patches:
https://github.com/CnCNet/ts-patches/blob/master/src/scale_movie_fix.c
https://github.com/CnCNet/ts-patches/blob/master/src/scale_movie_fix_hack.asm

**Comment by CCHyper** [comment] 2021-06-07 11:12
I'm not able to reproduce this, does anyone have any more information for this issue?

**Comment by CCHyper** [comment] 2021-06-13 21:22
Ok, seeing as there isn't more information, I'm going to assume that this issue will have been fixed with pull request #293 rewrite of the scaling algorithm.

If more information is to come up in the future that shows otherwise, we can reopen this.

**Closed by CCHyper** 2021-06-13 21:22 UTC
Labels: vanilla-bug
